const remainMoney = 100 - 40;
const pensilUse = 10 / 2;
const investMoneyTime = 60 / 15;
const remainInvestMoney = 60 % 15;
const hlwWorld = "Hello" + "World";
const totalWeight = 153 + 261;
const korochKorteParbo = 500 / 75;
const korochKorarPorTaka = 500 % 75;
const bagfol1 = 8 / 3;
const bagsesh1 = 8 % 3;
const bagfol2 = 50 / 9;
const bagsesh2 = 50 % 9;
const bd = "Bangla" + "desh";
const bhatThakbe = 480 / 4;
const mash = bhatThakbe / 30;

console.log(remainMoney);
console.log(pensilUse);
console.log(investMoneyTime);
console.log(remainInvestMoney);
console.log(hlwWorld);
console.log(totalWeight);
console.log(korochKorteParbo);
console.log(korochKorarPorTaka);
console.log(bagfol1);
console.log(bagsesh1);
console.log(bagfol2);
console.log(bagsesh2);
console.log(bd);
console.log(bhatThakbe);
console.log(mash);